name: main release
run-name: ${{ github.actor }} is releasing feature
on: 
  push:
    tags: 
      - v*.*.*
jobs:
  ci-main:name: main release
run-name: ${{ github.actor }} is releasing main
on:
  push:
    tags:
      - v*.*.*
jobs:
  ci-main:
    runs-on: ubuntu-latest
    env:
      REF_NAME: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup git user
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: Setup environment variables
        run: |
          VERSION="${REF_NAME#refs/heads/v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BRANCH_NAME=b${VERSION}" >> $GITHUB_ENV
          echo "TAG_NAME=v${VERSION}" >> $GITHUB_ENV
      - name: Release main
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"

      - name: Set enviroment variables
        runs: |
          VERSION="${REF_NAME#refs/heads/b}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BRANCH_NAME=b${VERSION}" >> $GITHUB_ENV
          echo "TAG_NAME=v${VERSION}" >> $GITHUB_ENV

      - name: Release main
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RE_TOKEN}}